# Generated by Django 2.1.7 on 2019-03-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightinput', '0002_auto_20190303_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloth',
            name='link_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloth',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloth',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloth',
            name='store_item_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
